### ISSUE TITLE
TypeError: Cannot assign to read only property '0' of string '[]'   [undefined:1]

### ISSUE THREAD

**Issue by overmike** [smashtestio/smashtest#10]
After I open chrome and nav to my local env, I can't find any element in the page and the screenshot looks fine. 

I have tried to use chrome/firefox/safari, my page definitely contains a button. 

Below is using REPL to select a button but in vain.

```
> 'button'

Start:     'button'
End:       'button'     failed (0.01 s)


'button'
TypeError: Cannot assign to read only property '0' of string '[]'   [undefined:1]
    at Function.parseObj (/usr/local/lib/node_modules/smashtest/packages/js/elementfinder.js:337:28)
    at doFind (/usr/local/lib/node_modules/smashtest/packages/js/elementfinder.js:867:48)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async /usr/local/lib/node_modules/smashtest/packages/js/elementfinder.js:864:17


enter step to run it, enter or x = exit

```

**Comment by vptes1** [comment]
Is the button visible? By default it only searches among visible elements. Either way, the error message isn't correct (so it's definitely a bug)

**Comment by overmike** [comment]
I try to put a console.log in elementfinder.js:867
For fail case, the children is a string '[]'. for success case, it is an array
```
{
  line: 'input',
  counter: { min: 1, max: 1, default: true },
  props: '[{"prop": "input", "def": "selector", "input": "input"}]',
  children: '[]',
  fullStr: 'input',
  blockErrors: '[]',
  error: null
}
```

**Comment by vptes1** [comment]
Yea I think that's the problem. It should always be an array. That's a separate issue for why it's not finding your button, though.

**Comment by overmike** [comment]
here is the case for button,

```
{
  line: 'button',
  counter: { min: 1, max: 1, default: true },
  props: '[{"prop": "button", "def": "selector", "input": "button"}, {"prop": "visible", "def": "visible"}]',
  children: '[]',
  fullStr: 'button',
  blockErrors: '[]',
  error: 'not found (zero matches after `visible` applied)'
}
```

**Comment by vptes1** [comment]
I'm having trouble reproducing this. What version/OS are you using for each browser? Are you seeing this in all browsers?

**Comment by vptes1** [comment]
Also, do you only see this in the REPL or both the REPL and regular tests?

**Comment by overmike** [comment]
I move the JSON.stringify logic for ef in elementfinder.js L478-L482 (within driver.executeScript) to L836-L838 (outside driver.executeScript) and it can now find the element. I guess the function driver.executeScript() runs in the browser context and affected by a legacy javascript library in the page. That maybe why you can't reproduce it.
I would suggest minimizing running javascript through selenium driver, as we should not trust the test subject.
https://github.com/smashtestio/smashtest/blob/eede587f8e3d35aebffb323467923ff4fa76b7f2/packages/js/elementfinder.js#L478-L482

https://github.com/smashtestio/smashtest/blob/eede587f8e3d35aebffb323467923ff4fa76b7f2/packages/js/elementfinder.js#L836-L838

**Comment by vptes1** [comment]
You make a good point. Fixed in https://github.com/smashtestio/smashtest/commit/e4d80ad9228e2bd25ee2807f4e333ba569ba8f23

**Comment by overmike** [comment]
Thanks for fixing, it works for me now
