### ISSUE TITLE
run test show error when use frequency option

### ISSUE THREAD

**Issue by memoryza** [smashtestio/smashtest#11]
ReferenceError: Constants is not defined
when i run  smashtest [filename]  --min-frequency=med

e.g:
`Open Chrome
    nav to 'baidu.com'
        type 'test' into 'input[id=kw]' #low
            Click 'input[id=su]' #med
        
        type 'm' into 'input[id=kw]' #high
            Click 'input[id=su]' #med`

**Comment by vptes1** [comment]
Good find!! Fixed in https://github.com/smashtestio/smashtest/commit/97ff3439f07243ab98c739625eacf94aee6ad523
