### ISSUE TITLE
set viewport can't work

### ISSUE THREAD

**Issue by memoryza** [smashtestio/smashtest#14]
When the safari is set to iphonex , the browser still use pc mode access， element is not visible in the viewport, they cannot be clicked.

error:
  Error: Element not found in time

example:
`
open chrome
Open Safari
    
    iPhone X 
        nav to 'www.google.com.hk/search?q=test'
            type 'test' into 'input[name=q]'
                click 'button[type=button]'

`

**Comment by memoryza** [comment]
sorry, it's maybe not bug, when set device type is work.

**Comment by vptes1** [comment]
Unfortunately, all Safari can do is resize the viewport. Only Chrome can completely emulate a mobile browser.

**Comment by vptes1** [comment]
Since this is a webdriver limitation (and not a Smashtest limitation), I'm going to close this ticket. Please feel free to reopen if you feel there's more to be looked at or discussed.

**Comment by memoryza** [comment]
> feel free to reopen if you feel there's more to be lo

ok
