### ISSUE TITLE
mocking geolocation fail

### ISSUE THREAD

**Issue by memoryza** [smashtestio/smashtest#15]
setting latitude and longitude in browser or triggering positioning all indicate failure
![image](https://user-images.githubusercontent.com/2704726/62194723-040a2a80-b3ad-11e9-8ebc-a322e8ac4b90.png)

`open chrome

    nav to 'map.baidu.com'
        Mock location to latitude='43.8084544665' longitude='125.3441601259'
            click 'div[id=iploc]'
                click 'div[class="sure-btn sureLoc-btn locbtn"]'
                    wait '1' secs
                        click 'div[id=iploc]'
                            wait '2' secs
                                stop all mocks
                                    click 'div[id=iploc]'
                                        wait '3' secs              `

**Comment by vptes1** [comment]
I can't get it to connect to https://map.baidu.com/. I'll try again later.

**Comment by vptes1** [comment]
Still can't connect. The page is taking a very long time to load.

**Comment by memoryza** [comment]
> I can't connect to https://map.baidu.com/. I'll try again later.

you can change to google map try it
for example

`open chrome

    nav to 'www.google.com/maps'
        Mock location to latitude='43.8084544665' longitude='125.3441601259'
            wait '3' secs
                click 'button[id=widget-mylocation]'
                    wait '3' secs
                        stop all mocks
                            click 'button[id=widget-mylocation]'
                                wait '3' secs  `

**Comment by vptes1** [comment]
Fixed in https://github.com/smashtestio/smashtest/commit/d640b7d68b88e2746c790ff81dbe6f8254c82f8b
I don't think `Stop all mocks` will always send Google Maps back to your original coords, as it seems like it caches your coords. But calling `navigator.geolocation.getCurrentPosition()` after a `Stop all mocks` within Google Maps correctly gives me my original coords, and starting a fresh browser also gives me my original coords.

Please let me know if we're good to close, @memoryza

**Comment by memoryza** [comment]
> Fixed in [d640b7d](https://github.com/smashtestio/smashtest/commit/d640b7d68b88e2746c790ff81dbe6f8254c82f8b)
> I don't think `Stop all mocks` will always send Google Maps back to your original coords, as it seems like it caches your coords. But calling `navigator.geolocation.getCurrentPosition()` after a `Stop all mocks` within Google Maps correctly gives me my original coords, and starting a fresh browser also gives me my original coords.
> 
> Please let me know if we're good to close, @memoryza

now mock location within Google Maps correctly gives me。but  Google Maps always caches my coords when i stop `Stop all mocks and refresh ` browser
`
open chrome

    nav to 'www.google.com/maps'
        Mock location to latitude='43.8084544665' longitude='125.3441601259'
            wait '3' secs
                click 'button[id=widget-mylocation]'
                    wait '3' secs
                        stop all mocks
                            Refresh
                                click 'button[id=widget-mylocation]'
                                    wait '3' secs              
`

**Comment by memoryza** [comment]
> navigator.geolocation.getCurrentPosition()

how to use `navigator.geolocation.getCurrentPosition()` 。I didn't see how to use Windows objects. I try to  use  `g('navigator') ` in code block ，but it's not work

**Comment by vptes1** [comment]
`navigator.geolocation.getCurrentPosition()` is a function within the browser:
```
Get current position {
    await executeScript(function() {   // exec js in browser
        navigator.geolocation.getCurrentPosition(function(obj) {
            console.log(obj);   // this obj contains info on the current coords
        });
    });
}
```
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition

I don't think it's possible to do a `Stop all mocks` and refresh in Google Maps and get the original coords back. You'd have to restart the browser or just start a new test. I believe this is because of how Google Maps is implemented (and not a limitation of Smashtest).

**Comment by memoryza** [comment]
> `navigator.geolocation.getCurrentPosition()` is a function within the browser:
> 
> ```
> Get current position {
>     await executeScript(function() {   // exec js in browser
>         navigator.geolocation.getCurrentPosition(function(obj) {
>             console.log(obj);   // this obj contains info on the current coords
>         });
>     });
> }
> ```
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition
> 
> I don't think it's possible to do a `Stop all mocks` and refresh in Google Maps and get the original coords back. You'd have to restart the browser or just start a new test. I believe this is because of how Google Maps is implemented (and not a limitation of Smashtest).

ok，sorry，==! I made a mistake that I know this js API 。Just don't know how to use in .smash file.
I will try to use this code `Get current position {
    await executeScript(function() {   // exec js in browser
        navigator.geolocation.getCurrentPosition(function(obj) {
            console.log(obj);   // this obj contains info on the current coords
        });
    });
}`
mocking geolocation is ok, Maybe i can colse it
