### ISSUE TITLE
Allow Tabs?

### ISSUE THREAD

**Issue by WayneHiller** [smashtestio/smashtest#16]
In the Docs it states. Exactly 4 spaces for each indent (no tabs). I am curious why it does not allow Tab Characters and then just convert them to 4 characters internally during the parsing process?

**Comment by vptes1** [comment]
Different editors equate tabs to varying amount of spaces, so we wanted to keep things consistent.  Python's spec strongly recommends avoiding tabs for this very reason. If there's more demand for using tabs, however, we'll implement this.

**Comment by WayneHiller** [comment]
If you convert tab characters to exactly 4 spaces internally when parsing it would not matter what an editor does with tabs. In fact using tabs is the best way because it does not make any difference what the editor is set to. Seems very dangerous to require exactly 4 characters for indenting.

**Comment by sarimarton** [comment]
I've closed this for now.
