### ISSUE TITLE
How to combine `Verify` with element finder?

### ISSUE THREAD

**Issue by apauly** [smashtestio/smashtest#18]
I tried to just do a simple test like "Does the current page contain the users name?":

What I tried:
```
Verify 'body' contains 'John'
```

This returns an error:
```
Error: The function `Verify 'body' contains 'John'` cannot be found.
```

But this works:
```
Verify 'body' is visible
```

I read the `Verify steps`, `ElementFinders` and `Default ElementFinder props`, but for me it's not clear how to actually combine these? Is the `is visible` example on the `Verify steps` page something different than the `visible` `ElementFinder prop`?

Thanks and best
Alex

**Comment by vptes1** [comment]
One of these is probably what you're looking for:
`Verify ['John'] is visible` (it will search the whole body for an element containing 'John')
`Verify [body, 'John'] is visible`
`Verify "body, 'John'" is visible`
`Verify [body, contains 'John'] is visible`

The step `Verify {{elementfinder}} is visible` is what you need. If you want to wait longer than 1 sec to verify, use `Wait until {{elementfinder}} is visible`

You can post questions to the gitter chat at https://gitter.im/smashtestio/community and someone will be happy to help :)
