### ISSUE TITLE
Code refactoring suggestion for Tree.js 

### ISSUE THREAD

**Issue by okmanl** [smashtestio/smashtest#19]
Under `tree.js` in the `branchify()` module, lines 602-618
  

  
    branchify(stepNode, branchAbove, level, isFunctionCall, isSequential) {
        // ***************************************
        // 1) Initialize vars
        // ***************************************

        if(typeof branchAbove == 'undefined') {
            branchAbove = new Branch;
        }

        if(typeof level == 'undefined') {
            level = 0;
        }

        if(!stepNode.isFunctionDeclaration) {
            this.latestBranchifiedStepNode = stepNode;
        }

        isSequential = (stepNode.isSequential && !(stepNode instanceof StepBlockNode)) || isSequential; // is this step node or any step node above it sequential? (does not include sequential step blocks)

        // Rest of code

I believe can be refactored to just

 

    branchify(stepNode, branchAbove = new Branch, level = 0, isFunctionCall, isSequential = (stepNode.isSequential && !(stepNode instanceof StepBlockNode)) ) {
        // ***************************************
        // 1) Initialize vars
        // ***************************************
 
        if(!stepNode.isFunctionDeclaration) {
            this.latestBranchifiedStepNode = stepNode;
        } 
        // Rest of code

I've tried doing that and running all the tests, and it seems to work just fine for me. Also, is it fine to make tiny refactoring suggestions like this?

**Comment by vptes1** [comment]
Suggestions are always welcome! I personally think this is a stylistic preference (i.e., do you prefer logic to be in the default params vs. in the function body?). To be consistent with the rest of the code, let's keep it the same for now. But we may come back to this later and convert all initialization code to default parms.

**Comment by vptes1** [comment]
Come to think of it, I like the `param = 0` thing. We should do that across the board. But I think that anything complex like `isSequential = (stepNode.isSequential && !(stepNode instanceof StepBlockNode))` should be in the function body.

**Comment by okmanl** [comment]
@vptes1 , Ok, I managed to refactor all functions that have variable initialization inside the function body to the function header.
