### ISSUE TITLE
[Bug] Navigation to 'localhost' fails

### ISSUE THREAD

**Issue by MartinJohns** [smashtestio/smashtest#2]
**Description:**

Navigation to localhost fails with the following error message:

```
Navigate to "http://localhost:4200/"
Error: Cannot determine domain to navigate to. Either include a domain or have the browser already be at a page with a domain.   [C:\project-path\helloworld.smash:3]
    at BrowserInstance.nav (C:\long-path\smashtest\packages\js\browserinstance.js:274:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Version:** `smashtest@1.0.16-beta`

**Example `.smash` file:**

```
Open Chrome

    Navigate to "http://localhost:4200/"
```

**Problem:**

Your regular expression to parse the URL is broken: https://github.com/smashtestio/smashtest/blob/c7c491b42e6e98712019c0dd5f7802bad93709c8/packages/js/browserinstance.js#L261

You're assuming the domain contains at least one `.` character, which is no requirement for domains.

![Visualization of the regular expression](https://i.imgur.com/TlmEuzE.png)

**Comment by vptes1** [comment]
Fixed in https://github.com/smashtestio/smashtest/commit/43a1bcc65a68909c0e42029ea3ce8302e43903eeThank you!
