### ISSUE TITLE
how to use command line --debug

### ISSUE THREAD

**Issue by Ariska138** [smashtestio/smashtest#24]
when I run 

`smashtest test.smash --screenshots=false --debug`

I dont know how to find value hash. 

`Error: debug flag must be set to a hash
    at Object.exports.error (/usr/lib/node_modules/smashtest/src/utils.js:39:15)
    at processFlag (/usr/lib/node_modules/smashtest/src/cli.js:120:27)
    at /usr/lib/node_modules/smashtest/src/cli.js:384:17
`
can anyone give me sample code?

**Comment by vptes1** [comment]
Hi there - The smashtest gitter is the best place to ask questions of this sort https://gitter.im/smashtestio/community

Are you trying to run a single branch in debug mode? If so, go into the report, open the branch you want to run, press "h", and that will copy the hash of the branch to the clipboard. Then paste it into the command line, e.g., `smashtest --debug=a3638bc74728fba737`
