### ISSUE TITLE
Typing into multiple browsers simultaneously intermittently causes ECONNREFUSED error

### ISSUE THREAD

**Issue by vptes1** [smashtestio/smashtest#30]
```
Open Chrome

    Define locators {
        props({
            'search box': `xpath '//input[@name="q"]'`,
            'search button': `xpath '(//input[@name="btnK"])[1]'`
        });
    }

        Navigate to "google.com"

            Type "Hello" into 'search box'
            Type "Hello" into 'search box'
            Type "Hello" into 'search box'
            Type "Hello" into 'search box'
            Type "Hello" into 'search box'
```
causes all branches to fail with
```
Type "Hello" into 'search box'
Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:61199   [testfile.smash:13]
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/smashtest/node_modules/selenium-webdriver/http/index.js:258:15)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at Socket.socketErrorListener (_http_client.js:391:9)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Errors occur intermittently and only with Chrome. Reproduced on MacOS.
No errors occur when only one branch does a `Type`.
No errors occur with other kinds of steps, such as `Click`.
Occurs less frequently when screenshots are off, or when not in headless mode.

**Comment by vptes1** [comment]
Errors don't occur when I do
```
Type "Hi" into 'search box'
            
Click 'search box'
    Type "Hello" into 'search box'
```
leading me to believe that both `Type` commands have to occur at the same exact time

**Comment by vptes1** [comment]
I'm only able to repro when screenshots are on

**Comment by vptes1** [comment]
Problem seems to be exacerbated when there are more parallel branches trying to do a screenshot + type, simultaneously.

It also gets worse the longer the wait in browserinstance.js/takeScreenshot(), such as the Jimp-related `await` (it can be replaced with a sleep and it will have the same effect).

ECONNREFUSED seems to occur when a `takeScreenshot()` is attempted in the `Before Every Step` called before each `Type` step. My gut tells me that headless chromedriver cannot handle screenshots and types mixed together amongst different windows (maybe it's a focus-related thing?).

**Comment by vptes1** [comment]
Seems to work properly when env var `SELENIUM_SERVER_JAR` is properly set, per https://smashtest.io/getting-started/setup, Option 1.

If noone sees this error for a few more days, I'll close the ticket.

**Comment by sarimarton** [comment]
I'm running into this. It's very flaky, apparently nothing to do with screenshots, it does it with screenshots=false too. I'm trying to mitigate with a very manual Wait step, but it doesn't solve it. It happens typically around a Type step.

Chrome version is Mac / 87.0.4280.67 (Official Build) (x86_64)
chromedriver@87.0.0
smashtest@1.7.0

```
* Wait {
    await new Promise(r => setTimeout(r, 2500));
}

* Login
    ..
    Navigate to 'https://local./* ... */.com/login'
    Wait
    Type 'x2@x2.com' into [input, 'email']
    Wait
    Click [button, 'Continue']
    Wait
    Type '/* ... */' into [input, 'password']
    Wait
    Click [button, 'Continue']
    Wait until at page '/activity'

* Init ..
    Open Chrome
    Laptop L
    Login

Init
    Click [button, 'new project']
    Navigate to 'https://local./* ... */.com/some/page'

        Wait
            Verify [button, 'Publish'] is visible
```

**Comment by sarimarton** [comment]
Disabling parallel run is a workaround.

**Comment by sarimarton** [comment]
I can confirm that Option 1 works as mentioned in https://github.com/smashtestio/smashtest/issues/30#issuecomment-547026055

However it was misleading that on MacOS the Setup guide mentions `npm install -g webdriver-manager` which didn't work for me. Maybe it was me, but the Windows sections worked (`npm install -g selenium-standalone`)
