### ISSUE TITLE
Show "JavaScript error" when running samshtest on the IE

### ISSUE THREAD

**Issue by yannarong** [smashtestio/smashtest#31]
**After running below codes:**
Open IE

    Maximize window
        nav to "www.google.com"
            Wait until 'input[id=fakebox-input]' is visible (up to '10000' secs)
**Show error:**
Wait until 'input[id=fakebox-input]' is visible (up to '10000' secs)
JavascriptError: JavaScript error   [F:\smashtestdemo\test\demo.smash:5]

**Comment:**
No such error for FireFox or safari.

**Comment by vptes1** [comment]
What version of smashtest and IE are you using? Also, can you please provide more details on the error? (i.e., a stack trace, line numbers)

**Comment by yannarong** [comment]
Hi below are the versions:

·         IE 11, version 11.1176.10586

·         IEdriver version is 3.9.0.

·         smashtest:1.0.23-beta


Full log please see the attachment.

**Comment by vptes1** [comment]
We had a similar bug filed for smashtest 1.0 that has since been fixed. Please upgrade to the latest version of smashtest and let us know if that fixed the problem.

**Comment by yannarong** [comment]
Yeah. Now it works after updating the version.
Thanks very much!
