### ISSUE TITLE
[Docs] Is there a way to include other .smash files?

### ISSUE THREAD

**Issue by amesas** [smashtestio/smashtest#32]
We can use *** Before Everything to include .js files.

But what about .smash files?

**Comment by vptes1** [comment]
When you declare a function at indent 0 in a .smash file, it is accessible
in all other .smash files. You just have to make sure all of those files
are included when you run `smashtest` from the command line.

**Comment by amesas** [comment]
So the formal way it to pass more than one file at command line.

I have just seen it in a phrase around the docs. You must read the docs line by line to find some of these features. :)
