### ISSUE TITLE
[Question] Code block - count elements

### ISSUE THREAD

**Issue by amesas** [smashtestio/smashtest#33]
First, can we execute code blocks inside REPL mode?

And now, how can I store in a variable the number of elements in a page?

Like:

Get rows in table {
 g('myvar', (await $$('tr.myclass')).length)
}
Whenever I try to log() those vars or await $$('tr.myclass')).length, I get no output in the report.

**Comment by vptes1** [comment]
1. Yes you can. Type in `Something {`, enter, the code, enter, `}`, enter, and it will run. In fact, you don't even need to type in "Something". Just start with `{`.

2. You're doing it correctly. Does the step fail when you do that?

**Comment by amesas** [comment]
It doesn't fails, I just get no log.

Next step was a verify comparing different values but as I can't log it, not sure if I'm reading it ok.

**Comment by amesas** [comment]
I run un debug mode ( ~ ).
dummy {
log('output');
}
Does "nothing" in REPL console. Not sure if i'm doing some wrong.

PS: Would be great being able to write a onliner like: dummy { log('output'); }

**Comment by vptes1** [comment]
Try using `c('Value: ' + (await $$('tr.myclass')).length)` instead of `log()`. It should output the value to the console.

**Comment by vptes1** [comment]
log() only outputs to the logs in the report. Click a step in the report to see its logs (on the right-hand panel).

**Comment by amesas** [comment]
True! My fault!
