### ISSUE TITLE
[Question] Best way to organize tests

### ISSUE THREAD

**Issue by amesas** [smashtestio/smashtest#34]
We have a lot of tests cases.

case1.smash
case2.smash
case3.smash
a common.smash with some helper functions.
and a setup.smash

In every case?.smash we don't want to open browser / login to our site.

What would be the best way to organize it? Is there an example showing this situation?

We have defined one function for each case?.smash file, but how can we each case selectively? Having a group for each case?

Thnx in advance for your help!

**Comment by vptes1** [comment]
Please check out https://smashtest.io/language/groups-and-freq for info on how to group tests and selectively run groups

**Comment by amesas** [comment]
Is that the only way?

What happens if i have hundreds/thousands of tests and I only want to run one of them?

I should have to add a group for each test.

**Comment by vptes1** [comment]
For that please use `$` https://smashtest.io/language/only

Also, if you have questions regarding use, the best place to ask them is the Smashtest Gitter: https://gitter.im/smashtestio/community
