### ISSUE TITLE
[CLI] Change report location

### ISSUE THREAD

**Issue by amesas** [smashtestio/smashtest#35]
Having a --report-location ( or similar ) that allows us to change the default ./smashtest/report.html

**Comment by juliensz** [comment]
It will happen with the history change that I wrote, we will be able to change the path of the report.

```
case "report-root":
    if(!value.match((/^(.*?)[\\\/]([^\\\/]+[a-zA-Z])$/) || (/^[^\/\: ]+(\:[0-9]+)?$/))) {
        utils.error(`Invalid path report folder. It must be absolute 'path', 'domain' or 'domain:port'.`);
    }
    reporter.reportPath = value;
    break;
case "history":
    reporter.history = boolValue();
    break;
```

**Comment by juliensz** [comment]
Is on :
--report-history=[true/false]
--report-path="[absolute path]"

**Comment by amesas** [comment]
Thnx, testing it right now! :)

**Comment by amesas** [comment]
It works fine for me!

Is there an way to know "the absolute path" for the current execution?

This part: smashtest-2019-10-19T19-34-04

We are integrating it in a CI/CD environment and we would like to link the report from it.

For now we are parsing stdout and read it from this line. Live report at: /path

**Comment by vptes1** [comment]
@amesas awesome! Feel free to close this ticket when you feel ready

I don't know of any other way other than reading stdout, like you said. Always open to new suggestions.

**Comment by amesas** [comment]
Closing it, as it resolves original request :)

One option could be history=off but being able to pass full path "/smashtest/mycustomtimestamp/"+ report.html and not only the "/smashtest/" location.

**Comment by amesas** [comment]
Right now I can get the final report location, after the test has been started.

Would be great being able to get/set the path before, so we can simply add a link to the live report.

Right now we have to execute the test async, capture the url, etc.

Is it a corner case? Or could be useful for more people?

**Comment by juliensz** [comment]
> Right now I can get the final report location, after the test has been started.
> 
> Would be great being able to get/set the path before, so we can simply add a link to the live report.
> 
> Right now we have to execute the test async, capture the url, etc.
> 
> Is it a corner case? Or could be useful for more people?

If you set History to false (default), you can know the path before test run, but if you set history on true is more difficult, smashtest generates itself the name of the file for the historization.

But at the moment I am working on a solution to longer therme to be able to add remote server (AWS, google cloud, other, ...) and suddenly at the same time to see access via a URL and a cleaner backup.

If you have an idea of ​​how you can manage more easily, I'm interested
