### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [smashtestio/smashtest#4]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/smashtestio/smashtest/blob/master/package.json#L39

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by vptes1** [comment]
Fixed in https://github.com/smashtestio/smashtest/commit/fcd9691fcb92a5fdc248f6d6271191c8ede2ad26

Thank you!
