### ISSUE TITLE
Use crypto for md5 hash generation instead of using the md5 package

### ISSUE THREAD

**Issue by DanielRuf** [smashtestio/smashtest#5]
We can use the crypto package which is part of the NodeJS core ´modules to generate md5 hashes.

```
const crypto = require('crypto');

const md5sum = crypto.createHash('md5').update(string).digest('hex');
```

https://github.com/DanielRuf/snippets/blob/master/checksums.js#L4

**Comment by vptes1** [comment]
Fixed in https://github.com/smashtestio/smashtest/commit/fcd9691fcb92a5fdc248f6d6271191c8ede2ad26
Thank you!
