### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by vptes1** [smashtestio/smashtest#54]
Installer that downloads and sets up smashtest, selenium webdriver, and other dependencies according to https://smashtest.io/getting-started/setup

**Comment by sarimarton** [comment]
I don't think it's necessary now, time has passed and lots of things happened.

As of v1.9.0, nothing else is needed for a fully functional test suite, other than smashtest (and trivially, nodejs).

- Chrome team released Chrome for Testing, which provides binary URLs for specific versions
- selenium-webdriver caught up on this and they're downloading Chrome and the matching chromedriver automatically on-demand to ~/.cache
- Smashtest has selenium-webdriver as a regular dependency, so everything works seemlessly.

The website has lots of deprecated information.
