### ISSUE TITLE
How to override default timeout

### ISSUE THREAD

**Issue by shibupanda** [smashtestio/smashtest#60]
Getting below error.

Error: Timeout of 60s exceeded   [/home/radmin/Pictures/SmashTest/helloworld.smash:16]

Is there any capabilities to override default timeout?

**Comment by vptes1** [comment]
Please check setStepTimeout() at the bottom of https://smashtest.io/language/code-reference

Also, feel free to ask questions on the Smashtest gitter chat. GitHub is reserved for tasks and bugs.
