### ISSUE TITLE
Error: Server terminated early with status 1

### ISSUE THREAD

**Issue by tundeadex** [smashtestio/smashtest#63]
Hi There, 

I wonder if someone can help me here. 

My issue is, when i execute tests sequentially, only one  branch get executed successfully, and failed the remaining branches without launching the browser and throw the below errors.  Where there are multiple tests to execute, up to 2 branches are successfully executed then subsequent branches are failed without executing the scripts.

Please what can i do to resolve the issue?
Thank you

" Login                                                SampleTest.smash:4 --> helloworld.smash:3
  Open Chrome                                        helloworld.smash:6 --> browser.smash:19

**Open Chrome
Error: Server terminated early with status 1   [C:/Users/adeT/Test/helloworld.smash:6]**
    at C:\Users\adeT\AppData\Roaming\npm\node_modules\smashtest\node_modules\selenium-webdriver\remote\index.js:251:52
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

█████████████████████████ 100% | 00:00:37 | 1 passed | 1 failed | 2 branches complete

**Comment by craigvl** [comment]
Are you able to provide a link to your code?
