### ISSUE TITLE
Feature request: add easy way to match inside another element

### ISSUE THREAD

**Issue by unikitty37** [smashtestio/smashtest#65]
I'm trying to write something along the lines of

```
Click 'Privacy Policy', inside selector 'footer .legal'
```

but there doesn't seem to be a way to do it. (The aim is to guarantee that the "Privacy Policy" link clicked is definitely the one in the footer, regardless of what else is on the page.)

This is the best I've managed so far, but it just says `Error: The function `Click footer privacy policy link` cannot be found.`

```
Open Chrome

    Desktop
    Mobile

        Navigate to the site

            - Check the privacy policy

                Click footer privacy policy link

                    Verify at page 'Privacy Policy | Western Sussex CAMRA'

* Navigate to the site {
    props({
        'footer privacy policy link': selector '#page-content > footer .legal a', contains exact 'Privacy Policy'
    })
    Navigate to 'localhost:3000'
}
```

(I've tried working through the tutorial videos, but I don't learn very well from videos as they take so much time, which I don't have a load of — I find it much easier to learn from written articles. Are there transcripts available?)

**Comment by craigvl** [comment]
I think that you are missing the quotes around the Click call try:

`Click 'footer privacy policy link'`

**Comment by unikitty37** [comment]
Thanks — that's fixed it 👍
