### ISSUE TITLE
Using groups multiple times in Smashtest results in groups being ignored, and many branches being run

### ISSUE THREAD

**Issue by mendhak** [smashtestio/smashtest#69]
I've noticed that using a group name multiple times in Smashtest branches results in many branches being run and the group getting ignored.   

It's likely that I'm misunderstanding the purpose of groups, but I didn't see [anything on the documentation page](https://smashtest.io/language/groups-and-freq) about its purpose, so I've assumed it's some kind of filtering mechanism.  

Please help me understand why this would be happening.  

I've got a sample, just pretend that this is a deep test. 

```
Open Chrome

    Navigate to 'https://www.w3.org/' #first

        // Pretend there's a bunch of other steps here. 

        Click [a, 'Participate'] #first
        Click [a, 'Standards']  #second

```

Now try running it with `first` group. 

```
smashtest --groups="first"
```

This runs both branches.  I had expected this to run just the Click Participate step, not the Click Standards step.

**Comment by smashtestio** [comment]
Try removing the `#first` on the Navigate line. The `--groups="first"` argument will run ALL branches that contain a line marked with `#first`.

**Comment by mendhak** [comment]
The example is meant to be illustrative - where we have certain steps at the beginning that need the groups there, and certain steps at the end that also need a grouping.  Maybe this is a better example:

```
Open Chrome

    Navigate to 'https://www.w3.org/' #first
    Navigate to 'https://www.example.com/' #second

        // Pretend there's a bunch of other steps here. 

        Click [a, 'Participate'] #first
        Click [a, 'Standards']  #second
```

If you try this it finds 3 branches to run.  I had expected just one branch to run.  

Your comment explains why: 

> The --groups="first" argument will run ALL branches that contain a line marked with #first.

Now I think I understand a bit better - it's like every possible branch is gathered up, and then filtered.  It's not a _pre_-filter.
