### ISSUE TITLE
Please push latest code, tags, changelog to Github

### ISSUE THREAD

**Issue by mendhak** [smashtestio/smashtest#83]
Hi authors, congrats on the 1.8.0 release.  Please can you push the latest code and the tags up to Github.  It can help us to see what the latest changes are, as we are encountering various issues and we're not sure what its relation with smashtest is. 

 A changelog would also be appreciated. Thanks!

**Comment by sarimarton** [comment]
Hi @mendhak,

Thanks for the feedback! Code is synced now with 1.8.1 with the npm package, tags are updated, and the changelog has been updated as well.

**Comment by mendhak** [comment]
Awesome, Cheers for that. I see a clue already to my problems, will try it tonight!
