### ISSUE TITLE
Logical AND for --groups

### ISSUE THREAD

**Issue by vptes1** [smashtestio/smashtest#9]
Multiple groups passed in via --groups="A,B,C" are currently ORed together, with branches from any one group selected to run.

Allow a logical AND, where only branches that belong to all groups listed are selected to run.

Perhaps the syntax should be --groups="A+B+C", where + and , can be combined and + takes priority (e.g., "A+B,C+D" runs branches part of A and B, or C and D)

**Comment by okmanl** [comment]
Hi @vptes1 can I please attempt to work on this issue? If I have any questions I'll write on the Gitter chat forum!

**Comment by vptes1** [comment]
Go for it!

**Comment by faso** [comment]
I'd love to try and work on this if it's not very urgent

**Comment by vptes1** [comment]
@faso Sure, feel free to assign this ticket to yourself

**Comment by faso** [comment]
I don't think I have enough permissions to do that, probably need to be a Collaborator for the repo to self-assign

**Comment by vptes1** [comment]
@faso Invite sent
